name: Deploy to DreamHost

on:
  push:
    branches:
      - main  # Change this if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH/Rsync
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: .
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}